# git-cliff configuration for hyprwhspr-rs changelog generation
[git]
tag_pattern = "v*"
commit_preprocessors = [
  { pattern = "^Merge pull request #([0-9]+) from .*", replace = "" }
]
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactors" },
  { message = "^docs", group = "Docs" },
  { message = "^test", group = "Tests" },
  { message = "^build", group = "Build" },
  { message = "^chore", group = "Chores" },
  { message = "", group = "Misc" }
]
protect_tags = true

[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file."
body = "\n{% if version %}## {{ version | trim_start_matches(prefix=\"v\") }} - {{ timestamp | date(format=\"%Y-%m-%d\") }}{% endif %}\n{% for group, commits in commits | group_by(attribute=\"group\") %}\n### {{ group }}\n{% for commit in commits %}- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=8, end=\"\") }})\n{% endfor %}\n{% endfor %}"
footer = "\n"
sort_groups = true

[remote]
url = "https://github.com/better-slop/hyprwhspr-rs"
